openapi: 3.0.1
info:
  title: Summary mode issue worklog
  version: '1.0'
  description: |
    此资源代表工作项工时。使用它来获取、创建、更新和删除工作项工时。
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /project/issues/{issueID}/workLog/summary/timesEstimated:
    post:
      summary: 汇总模式添加工作项预估工时
      operationId: 01-add-estimated-time-of-issues
      description: 汇总模式添加工作项预估工时
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
      requestBody:
        description: 汇总模式添加工作项预估工时的请求参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTimesEstimatedRequest'
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTimesEstimatedResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
  /project/issues/{issueID}/workLog/summary/timesEstimated/{timesEstimatedID}:
    put:
      summary: 汇总模式修改工作项预估工时
      operationId: 02-update-estimated-time-of-issues
      description: 汇总模式修改工作项预估工时
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
        - name: timesEstimatedID
          in: path
          description: 预估工时ID
          required: true
          schema:
            type: string
      requestBody:
        description: 汇总模式修改工作项预估工时的请求参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTimesEstimatedRequest'
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTimesEstimatedResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
    delete:
      summary: 汇总模式删除工作项预估工时
      operationId: 03-delete-estimated-time-of-issues
      description: 汇总模式删除工作项预估工时
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
        - name: timesEstimatedID
          in: path
          description: 预估工时ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTimesEstimatedResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
  /project/issues/{issueID}/workLog/summary/timesSpent:
    get:
      summary: 汇总模式工作项工时列表
      operationId: 04-get-a-list-of-issues-worklog
      description: 汇总模式工作项工时列表
      security:
        - oauth2:
            - read:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: 本次请求要返回的工作项工时数量
          schema:
            type: integer
        - name: cursor
          in: query
          description: 本次请求的起始位置
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesSpentListResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
    post:
      summary: 汇总模式添加工作项工时
      operationId: 05-add-spent-time-of-issues
      description: 汇总模式添加工作项工时
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
      requestBody:
        description: 汇总模式添加工作项工时的请求参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTimesSpentRequest'
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTimesSpentResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
  /project/issues/{issueID}/workLog/summary/timesSpent/{timesSpentID}:
    put:
      summary: 汇总模式修改工作项工时
      operationId: 06-update-spent-time-of-issues
      description: 汇总模式修改工作项工时
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: 工时ID
          required: true
          schema:
            type: string
      requestBody:
        description: 汇总模式修改工作项工时的请求参数
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTimesSpentRequest'
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTimesSpentResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
    delete:
      summary: 汇总模式删除工作项工时
      operationId: 07-delete-spent-time-of-issues
      description: 汇总模式删除工作项工时
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: 工时ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTimesSpentResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
    get:
      summary: 汇总模式工作项工时详情
      operationId: 08-get-spent-time-of-issues
      description: 汇总模式获取工作项工时详情
      security:
        - oauth2:
            - read:project:issue-timeSpent
      parameters:
        - name: teamID
          in: query
          description: 团队ID
          required: true
          schema:
            type: string
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: 工时ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTimesSpentResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
components:
  schemas:
    GetTimesSpentResponse:
      description: 获取汇总模式下的工作项工时详情
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        data:
          type: object
          description: 本次请求返回的数据
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
    DeleteTimesSpentResponse:
      description: 汇总模式下删除工作项工时的返回结果
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
    UpdateTimesSpentRequest:
      description: 汇总模式下更新工作项工时的请求参数
      type: object
      properties:
        hours:
          type: integer
          description: 工时，单位（小时）
        description:
          type: string
          description: 工时的描述
        startTime:
          type: integer
          description: 工时开始时间，单位（时间戳）
        owner:
          type: object
          description: 工时登记人
      example:
        hours: 1
        description: 'Sample Description'
        startTime: 1689055200
        owner: UWQR89ji
    UpdateTimesSpentResponse:
      description: 汇总模式下更新工作项工时的返回结果
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        data:
          type: object
          description: 本次请求返回的数据
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
    AddTimesSpentRequest:
      description: 汇总模式下更新工作项工时的请求参数
      type: object
      properties:
        hours:
          type: integer
          description: 工时，单位（小时）
        description:
          type: string
          description: 工时的描述
        startTime:
          type: integer
          description: 工时开始时间，单位（时间戳）
        owner:
          type: object
          description: 工时登记人
      example:
        hours: 1
        description: 'Sample Description'
        startTime: 1689055200
        owner: UWQR89ji
    AddTimesSpentResponse:
      description: 汇总模式下更新工作项工时的返回结果
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        data:
          type: object
          description: 本次请求返回的数据
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
    TimesSpentListResponse:
      description: 获取汇总模式下的工作项工时列表
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        data:
          type: object
          description: 本次请求返回的数据
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
          data:
            list:
              - description: 'Sample Description 1'
                hours: 1
                owner:
                  id: 'xx'
                  name: 'xx'
                startTime: 1689055200
              - description: 'Sample Description 2'
                hours: 2
                owner:
                  id: 'yy'
                  name: 'yy'
                startTime: 1689055300
            pageInfo:
              count: 2
              endCursor: 'sample_end_cursor'
              hasNextPage: false
              startCursor: 'sample_start_cursor'
              totalCount: 2
    AddTimesEstimatedRequest:
      description: 汇总模式下添加预估工时的请求参数
      type: object
      properties:
        hours:
          type: integer
          description: 添加预估工时，单位（小时）
        startDate:
          type: string
          description: 预估工时开始时间，格式为YYYY-MM-DD
        endDate:
          type: string
          description: 预估工时结束时间，格式为YYYY-MM-DD
        owner:
          type: object
          description: 预估工时登记人
        includeNonWorkingDays:
          type: boolean
          description: 是否包含非工作日
        timesEstimatedMode:
          type: string
          enum:
            - total
            - daily
          description: |
            - total: 从开始日期到结束日期的预计总时间
            - daily: 从开始日期到结束日期每天的预计时间
      example:
        hours: 1
        startDate: '2023-01-01'
        endDate: '2023-01-31'
        owner: UWQR89ji
        includeNonWorkingDays: true
        timesEstimatedMode: daily
    AddTimesEstimatedResponse:
      description: 汇总模式下添加预估工时的返回结果
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        data:
          type: object
          description: 本次请求返回的数据
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
          data:
            hours: 1
            startDate: '2023-01-01'
            endDate: '2023-01-31'
            owner: UWQR89ji
            includeNonWorkingDays: true
            timesEstimatedMode: daily
    UpdateTimesEstimatedRequest:
      description: 汇总模式下更新预估工时的请求参数
      type: object
      properties:
        hours:
          type: integer
          description: 更新预估工时，单位（小时）
        startDate:
          type: string
          description: 预估工时开始时间，格式为YYYY-MM-DD
        owner:
          type: object
          description: 预估工时登记人
      example:
        hours: 1
        startDate: '2023-01-02'
        owner: UWQR89ji
    UpdateTimesEstimatedResponse:
      description: 汇总模式下更新预估工时的返回结果
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        data:
          type: object
          description: 本次请求返回的数据
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
          data:
            hours: 1
            startDate: '2023-01-02'
            endDate: '2023-01-31'
            owner: UWQR89ji
            includeNonWorkingDays: true
            timesEstimatedMode: daily
    DeleteTimesEstimatedResponse:
      description: 汇总模式下删除预估工时的返回结果
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果,SUCCESS|FAIL
        errorCode:
          type: string
          description: 本次请求错误码
        errorMsg:
          type: string
          description: 本次请求错误信息
      example:
        - result: SUCCESS
    $ref: ../../../../../../openapi-common/canary/zh/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            write:project:issue-timeEstimated: 新增、修改、删除工作项预估工时
            write:project:issue-timeSpent: 新增、修改、删除工作项登记工时
            read:project:issue-timeSpent: 获取工作项的登记工时信息
