openapi: 3.0.1
info:
  title: Testcase Library
  version: '1.0'
  description: |
    此资源代表测试用例库。使用它来获取、创建、更新和删除测试用例库。
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /testcase/libraries:
    get:
      summary: 获取测试用例库列表
      operationId: 01-get-a-list-of-test-case-libraries
      description: 获取测试用例库列表
      security:
        - oauth2:
            - read:testcase:library
      parameters:
        - $ref: ../../../../../../openapi-common/canary/zh/request-team.yaml
        - $ref: ../../../../../../openapi-common/canary/zh/paging-query-request-limit.yaml
        - $ref: ../../../../../../openapi-common/canary/zh/paging-query-request-cursor.yaml
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
    post:
      summary: 新建测试用例库
      operationId: 02-create-a-new-test-case-library
      description: 新建测试用例库
      security:
        - oauth2:
            - write:testcase:library
      parameters:
        - $ref: ../../../../../../openapi-common/canary/zh/request-team.yaml
      requestBody:
        description: 要新建的测试用例库信息
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddOrUpdateRequestLibrary'
        required: true
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
      x-codegen-request-body-name: body
  /testcase/libraries/{libraryID}:
    get:
      summary: 获取测试用例库详细信息
      operationId: 03-get-a-test-case-library-details
      description: 获取测试用例库详细信息
      security:
        - oauth2:
            - read:testcase:library
      parameters:
        - $ref: ../../../../../../openapi-common/canary/zh/request-team.yaml
        - name: libraryID
          in: path
          description: 测试用例库ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
    put:
      summary: 更新测试用例库
      operationId: 04-update-a-test-case-library
      description: 更新测试用例库
      security:
        - oauth2:
            - write:testcase:library
      parameters:
        - $ref: ../../../../../../openapi-common/canary/zh/request-team.yaml
        - name: libraryID
          in: path
          description: 测试用例库ID
          required: true
          schema:
            type: string
      requestBody:
        description: 要更新的测试用例库信息
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddOrUpdateRequestLibrary'
        required: true
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
      x-codegen-request-body-name: body
    delete:
      summary: 删除测试用例库
      operationId: 05-delete-a-test-case-library
      description: 删除测试用例库
      security:
        - oauth2:
            - write:testcase:library
      parameters:
        - $ref: ../../../../../../openapi-common/canary/zh/request-team.yaml
        - name: libraryID
          in: path
          description: 测试用例库ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        $ref: ../../../../../../openapi-common/canary/zh/no-200-response.yaml
      x-scope: write:testcase:library
components:
  schemas:
    AddOrUpdateRequestLibrary:
      type: object
      properties:
        caseFieldConfigurationID:
          maxLength: 8
          minLength: 1
          type: string
          description: 测试用例库字段配置ID
        name:
          maxLength: 32
          minLength: 1
          type: string
          description: 测试用例库名称
      example:
        name: Testcase Library
        caseFieldConfigurationID: safia765
    DeleteResponse:
      type: object
      properties:
        $ref: ../../../../../../openapi-common/canary/zh/200-response-schemas.yaml
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied delete_library'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied testcase_view_library'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound TestCaseLibrary'
    GetResponse:
      description: 测试用例库详细信息
      type: object
      properties:
        $ref: ../../../../../../openapi-common/canary/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            name:
              type: string
              description: 测试用例库名称
            id:
              type: string
              description: 测试用例库ID
            createTime:
              type: integer
              description: 测试用例库创建时间
            updateTime:
              type: integer
              description: 测试用例库更新时间
            stickToTop:
              type: boolean
              description: 测试用例库是否置顶
            testcaseFieldConfig:
              type: object
              properties:
                name:
                  description: 测试用例库字段配置名称
                  type: string
                id:
                  type: string
                  description: 测试用例库配置ID
              description: 测试用例库字段配置信息
      example:
        - result: SUCCESS
          data:
            name: Testcase Library
            id: safia765
            createTime: 1616592000
            updateTime: 1616592000
            stickToTop: false
            caseFieldConfigurationID: safia765
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound TestCaseLibrary'
    AddResponse:
      type: object
      properties:
        $ref: ../../../../../../openapi-common/canary/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            name:
              type: string
              description: 测试用例库名称
            id:
              type: string
              description: 测试用例库ID
            createTime:
              type: integer
              description: 测试用例库创建时间
            updateTime:
              type: integer
              description: 测试用例库更新时间
            stickToTop:
              type: boolean
              description: 测试用例库是否置顶
            caseFieldConfigurationID:
              type: string
              description: 测试用例库字段配置ID
      example:
        - result: SUCCESS
          data:
            name: Testcase Library
            id: safia765
            createTime: 1616592000
            updateTime: 1616592000
            stickToTop: false
            caseFieldConfigurationID: safia765
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied manage_library'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound caseFieldConfigurationID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter TestCaseLibrary Library Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter TestCaseLibrary Name TooLong'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter TestCaseLibrary caseFieldConfigurationID InvalidFormat'
    UpdateResponse:
      type: object
      properties:
        $ref: ../../../../../../openapi-common/canary/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            name:
              type: string
              description: 测试用例库名称
            id:
              type: string
              description: 测试用例库ID
            createTime:
              type: integer
              description: 测试用例库创建时间
            updateTime:
              type: integer
              description: 测试用例库更新时间
            stickToTop:
              type: boolean
              description: 测试用例库是否置顶
            caseFieldConfigurationID:
              type: string
              description: 测试用例库字段配置ID
      example:
        - result: SUCCESS
          data:
            name: Testcase Library
            id: safia765
            createTime: 1616592000
            updateTime: 1616592000
            stickToTop: false
            caseFieldConfigurationID: safia765
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied manage_library'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound TestCaseLibrary'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound caseFieldConfigurationID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter TestCaseLibrary Library Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter TestCaseLibrary Name TooLong'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter TestCaseLibrary caseFieldConfigurationID InvalidFormat'
    ListItem:
      type: object
      properties:
        name:
          type: string
          description: 测试用例库名称
        id:
          type: string
          description: 测试用例库ID
        createTime:
          type: integer
          description: 测试用例库创建时间
        updateTime:
          type: integer
          description: 测试用例库更新时间
        stickToTop:
          type: boolean
          description: 测试用例库是否置顶
        testcaseFieldConfig:
          type: object
          properties:
            name:
              description: 测试用例库字段配置名称
              type: string
            id:
              type: string
              description: 测试用例库配置ID
          description: 测试用例库字段配置信息
    ListResponse:
      type: object
      properties:
        $ref: ../../../../../../openapi-common/canary/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/ListItem'
            $ref: ../../../../../../openapi-common/canary/zh/paging-query-response-pageInfo-schemas.yaml
    $ref: ../../../../../../openapi-common/canary/zh/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            write:testcase:library: 新增、修改、删除用例库
            read:testcase:library: 获取用例库信息
