openapi: 3.0.1
info:
  title: Simple mode issue worklog
  version: '1.0'
  description: |
    This resource represents issue worklog in simple mode. Use it to get, create, update, and delete issue worklog.
servers:
  - url: https://your-domain/openapi/v1
  - url: http://your-domain/openapi/v1
paths:
  /project/issues/{issueID}/workLog/simple/timesEstimated:
    post:
      summary: Estimated time in simple mode
      operationId: 01-estimated-time-of-issues
      description: Estimated time in simple mode.
      security:
        - oauth2:
            - write:project:issue-timeEstimated
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Estimated time in simple mode.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimesEstimatedRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesEstimatedResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
  /project/issues/{issueID}/workLog/simple/timesRemaining:
    post:
      summary: Update remaining time in simple mode
      operationId: 02-update-remaining-time-of-issues
      description: Update remaining time in simple mode.
      security:
        - oauth2:
            - write:project:issue-timeRemaining
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Remaining time to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimesRemainingRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesRemainingResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
  /project/issues/{issueID}/workLog/simple/timesSpent:
    get:
      summary: Get a list of issues worklog in simple mode
      operationId: 03-get-a-list-of-issues-worklog
      description: Get a list of issues worklog in simple mode.
      security:
        - oauth2:
            - read:project:issue-timeSpent
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - $ref: ../../../../openapi-common/latest/en/paging-query-request-limit.yaml
        - $ref: ../../../../openapi-common/latest/en/paging-query-request-cursor.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesSpentListResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
    post:
      summary: Add spent times in simple mode
      operationId: 04-add-spent-time-of-issues
      description: Add spent times in simple mode.
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Add spent times to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTimesSpentRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTimesSpentResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
  /project/issues/{issueID}/workLog/simple/timesSpent/{timesSpentID}:
    put:
      summary: Update spent times in simple mode
      operationId: 05-update-spent-time-of-issues
      description: Update spent times in simple mode.
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: The timesSpent ID.
          required: true
          schema:
            type: string
      requestBody:
        description: Update spent times to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTimesSpentRequest'
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTimesSpentResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
    delete:
      summary: Delete spent times in simple mode
      operationId: 06-delete-spent-time-of-issues
      description: Delete spent times in simple mode.
      security:
        - oauth2:
            - write:project:issue-timeSpent
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: The timesSpent ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTimesSpentResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
    get:
      summary: Get a spent times in simple mode
      operationId: 07-get-spent-time-of-issues
      description: Get a spent times in simple mode.
      security:
        - oauth2:
            - read:project:issue-timeSpent
      parameters:
        - $ref: ../../../../openapi-common/latest/en/request-team.yaml
        - name: issueID
          in: path
          description: The issue ID.
          required: true
          schema:
            type: string
        - name: timesSpentID
          in: path
          description: The timesSpent ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Request is successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTimesSpentResponse'
        $ref: ../../../../openapi-common/latest/en/no-200-response.yaml
components:
  schemas:
    GetTimesSpentResponse:
      description: 'The result of get a spent time'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
        data:
          type: object
          description: The result of this request.
          properties:
            id:
              type: string
              description: The id of spent time.
            hours:
              description: The spent time,unit is hour.
              type: number
              format: float
              pattern: "^\\d+(\\.\\d{1,5})?$"
            description:
              type: string
              description: The description of spent time.
            startTime:
              type: integer
              description: 'The start time of spent time,Format: 1691043051'
            owner:
              type: object
              description: The owner of spent time.
              properties:
                id:
                  type: string
                  description: The id of spent time.
                name:
                  type: string
                  description: The name of spent time.
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner: UWQR89ji
            id: kkoi976k
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in summary mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours TooLong'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound timesSpentID'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Container'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
    DeleteTimesSpentResponse:
      description: 'The result of delete spent time'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in summary mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours TooLong'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound timesSpentID'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Container'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
    UpdateTimesSpentRequest:
      description: 'The request of update spent time'
      type: object
      properties:
        hours:
          description: The spent time,unit is hour.
          type: number
          format: float
          pattern: "^\\d+(\\.\\d{1,5})?$"
        description:
          type: string
          description: The description of spent time.
        startTime:
          type: integer
          description: 'The start time of spent time,Format: 1691043051'
        owner:
          type: object
          description: The owner of spent time.
      required:
        - hours
        - startTime
        - owner
      example:
        hours: 1
        description: 'Sample Description'
        startTime: 1689055200
        owner: UWQR89ji
    UpdateTimesSpentResponse:
      description: 'The result of update spent time'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
        data:
          type: object
          description: The result of this request.
          properties:
            id:
              type: string
              description: The id of spent time.
            hours:
              description: The spent time,unit is hour.
              type: number
              format: float
              pattern: "^\\d+(\\.\\d{1,5})?$"
            description:
              type: string
              description: The description of spent time.
            startTime:
              type: integer
              description: 'The start time of spent time,Format: 1691043051'
            owner:
              type: object
              description: The owner of spent time.
              properties:
                id:
                  type: string
                  description: The id of spent time.
                name:
                  type: string
                  description: The name of spent time.
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner:
              id: UWQR89ji
              name: 'Sample Name'
            id: kkoi976k
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in summary mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours TooLong'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound timesSpentID'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Container'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
    AddTimesSpentRequest:
      description: 'The request of add spent time'
      type: object
      properties:
        hours:
          description: The spent time,unit is hour.
          type: number
          format: float
          pattern: "^\\d+(\\.\\d{1,5})?$"
        description:
          type: string
          description: The description of spent time.
        startTime:
          type: integer
          description: 'The start time of spent time,Format: 1691043051'
        owner:
          type: object
          description: The owner of spent time.
      required:
        - hours
        - startTime
        - owner
      example:
        hours: 1
        description: 'Sample Description'
        startTime: 1689055200
        owner: UWQR89ji
    AddTimesSpentResponse:
      description: 'The result of add spent time'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
        data:
          type: object
          description: The result of this request.
          properties:
            id:
              type: string
              description: The id of spent time.
            hours:
              description: The spent time,unit is hour.
              type: number
              format: float
              pattern: "^\\d+(\\.\\d{1,5})?$"
            description:
              type: string
              description: The description of spent time.
            startTime:
              type: integer
              description: 'The start time of spent time,Format: 1691043051'
            owner:
              type: object
              description: The owner of spent time.
              properties:
                id:
                  type: string
                  description: The id of spent time.
                name:
                  type: string
                  description: The name of spent time.
      example:
        - result: SUCCESS
          data:
            hours: 1
            description: 'Sample Description'
            startTime: 1689055200
            owner:
              id: UWQR89ji
              name: 'Sample Name'
            id: kkoi976k
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in summary mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours TooLong'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Container'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
    TimesSpentListResponse:
      description: 'The result of estimated time.'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
        data:
          type: object
          description: The result of this request.
          properties:
            list:
              type: array
              description: 'List of items.'
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: 'Worklog id'
                  description:
                    description: 'Worklog description'
                    type: string
                  hours:
                    type: integer
                    description: 'Worklog hours,unit is hour'
                  owner:
                    type: object
                    properties:
                      id:
                        type: string
                        description: 'Times spent owner id'
                      name:
                        type: string
                        description: 'Times spent owner name'
                  startTime:
                    type: integer
                    description: 'Worklog start time'
            pageInfo:
              type: object
              description: 'Page information.'
              properties:
                count:
                  type: integer
                  description: The number returned this time.
                endCursor:
                  type: string
                  description: The last cursor on this page is generally used to turn pages.
                hasNextPage:
                  type: boolean
                  description: Is there a next page.
                startCursor:
                  type: string
                  description: The first cursor on this page is generally used to turn pages.
                totalCount:
                  type: integer
                  description: The total number of items available in the entire collection,
                    including those that are  returned in the current response.
      example:
        - result: SUCCESS
          data:
            list:
              - id: 'yuhbf780'
                description: 'Sample Description 1'
                hours: 1
                owner:
                  id: 'hgbko876'
                  name: 'xx'
                startTime: 1689055200
              - id: 'yuhbf781'
                description: 'Sample Description 2'
                hours: 2
                owner:
                  id: 'hgbko877'
                  name: 'yy'
                startTime: 1689055300
            pageInfo:
              count: 2
              endCursor: 'adsgfa8hsd0hdf'
              hasNextPage: false
              startCursor: 'dsoijioew09ewqkjb'
              totalCount: 2
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in simple mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter limit InvalidType'
    TimesEstimatedRequest:
      description: 'The request of estimated time'
      type: object
      properties:
        hours:
          type: number
          format: float
          pattern: "^\\d+(\\.\\d{1,5})?$"
          description: Estimated time,unit is hour.
      required:
        - hours
      example:
        hours: 1
    TimesEstimatedResponse:
      description: 'The result of estimated time'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in summary mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours TooLong'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Container'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
    TimesRemainingRequest:
      description: 'The request of update remaining time'
      type: object
      properties:
        hours:
          type: number
          format: float
          pattern: "^\\d+(\\.\\d{1,5})?$"
          description: Remaining time,unit is hour.
      required:
        - hours
      example:
        hours: 1
    TimesRemainingResponse:
      description: 'The result of update remaining time'
      type: object
      properties:
        $ref: ../../../../openapi-common/latest/en/200-response-schemas.yaml
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: Forbidden
          errorMsg: 'Unable to times estimated in summary mode'
        - result: FAIL
          errorCode: MissingParameter
          errorMsg: 'MissingParameter teamID'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours Empty'
        - result: FAIL
          errorCode: InvalidParameter
          errorMsg: 'InvalidParameter IssueWorkLog Hours TooLong'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound Container'
        - result: FAIL
          errorCode: AccessDenied
          errorMsg: 'AccessDenied Issue'
        - result: FAIL
          errorCode: 'Internal Server Error'
          errorMsg: 'Internal Server Error'
        - result: FAIL
          errorCode: PermissionDenied
          errorMsg: 'PermissionDenied super_administrator'
    $ref: ../../../../openapi-common/latest/en/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            write:project:issue-timeEstimated: Add, edit, delete time estimated for an issue
            write:project:issue-timeRemaining: Add, edit, delete time remaining for an issue
            write:project:issue-timeSpent: Add, edit, delete time spent for an issue
            read:project:issue-timeSpent: Obtain the worklog information for an issue
