openapi: 3.0.1
info:
  title: Issues
  version: '1.0'
  description: |
    此资源代表工作项。使用它来获取、创建、更新和删除工作项。
servers:
  - url: https://your-domain/openapi/v2
  - url: http://your-domain/openapi/v2
paths:
  /project/issues:
    get:
      summary: 获取工作项列表
      operationId: 01-get-a-list-of-issues
      description: 获取工作项列表
      security:
        - oauth2:
            - read:project:issue
      parameters:
        - $ref: ../../../../../../../openapi-common/latest/zh/request-team.yaml
        - $ref: ../../../../../../../openapi-common/latest/zh/paging-query-request-limit.yaml
        - $ref: ../../../../../../../openapi-common/latest/zh/paging-query-request-cursor.yaml
        - name: projectID
          in: query
          description: 作为过滤条件，列表只返回是projectID的工作项，与issueTypeID配合使用
          schema:
            type: string
        - name: issueTypeID
          in: query
          description: 作为过滤条件，列表只返回是issueTypeID的工作项，与projectID配合使用
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSuccessResponse'
        $ref: ../../../../../../../openapi-common/latest/zh/no-200-response.yaml
    post:
      summary: 新建工作项
      operationId: 02-create-a-new-issue
      description: 新建工作项
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../../../../../openapi-common/latest/zh/request-team.yaml
      requestBody:
        description: 要新建的工作项信息
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddIssueRequest'
        required: true
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddSuccessResponse'
        $ref: ../../../../../../../openapi-common/latest/zh/no-200-response.yaml
      x-scope: write:project:issue
      x-codegen-request-body-name: body
  /project/issues/{issueID}:
    get:
      summary: 获取工作项详细信息
      operationId: 03-get-a-issue-details
      description: 获取工作项详细信息
      security:
        - oauth2:
            - read:project:issue
      parameters:
        - $ref: ../../../../../../../openapi-common/latest/zh/request-team.yaml
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListItem'
        $ref: ../../../../../../../openapi-common/latest/zh/no-200-response.yaml
    put:
      summary: 更新工作项
      operationId: 04-update-a-issue
      description: 更新工作项
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../../../../../openapi-common/latest/zh/request-team.yaml
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
      requestBody:
        description: 要更新的工作项信息
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIssueRequest'
        required: true
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSuccessResponse'
        $ref: ../../../../../../../openapi-common/latest/zh/no-200-response.yaml
      x-codegen-request-body-name: body
    delete:
      summary: 删除工作项
      operationId: 05-delete-a-issue
      description: 删除工作项
      security:
        - oauth2:
            - write:project:issue
      parameters:
        - $ref: ../../../../../../../openapi-common/latest/zh/request-team.yaml
        - name: issueID
          in: path
          description: 工作项ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSuccessResponse'
        $ref: ../../../../../../../openapi-common/latest/zh/no-200-response.yaml
components:
  schemas:
    AddIssueRequest:
      required:
        - assignee
        - fieldValues
        - issueTypeID
        - projectID
        - title
        - watchers
      type: object
      properties:
        assignee:
          maxLength: 8
          minLength: 1
          type: string
          description: 工作项负责人
        title:
          maxLength: 1024
          minLength: 1
          type: string
          description: 工作项标题
        projectID:
          maxLength: 16
          minLength: 1
          type: string
          description: 工作项所属项目ID
        issueTypeID:
          maxLength: 8
          minLength: 1
          type: string
          description: 工作项类型ID
        fieldValues:
          type: array
          description: 工作项属性信息
          items:
            $ref: '#/components/schemas/FieldValues'
        watchers:
          type: array
          description: 当工作项发生变化时，将通过邮件等方式通知关注者
          items:
            maxLength: 8
            minLength: 1
            type: string
        parentID:
          maxLength: 16
          minLength: 1
          type: string
          description: 父工作项ID
      example:
        assignee: 5f1f3b91
        title: 测试工作项
        projectID: 5f1f3b913b9b9c87
        issueTypeID: njkib897
        fieldValues:
          - fieldID: 3b9b9c87
            value: '测试属性'
        watchers:
          - 5f1f3b91
    UpdateIssueRequest:
      type: object
      properties:
        assignee:
          maxLength: 8
          minLength: 1
          type: string
          description: 工作项负责人
        title:
          maxLength: 1024
          minLength: 1
          type: string
          description: 工作项负责人
        fieldValues:
          type: array
          description: 工作项属性信息
          items:
            $ref: '#/components/schemas/FieldValues'
      example:
        assignee: 5f1f3b91
        title: 测试工作项
        fieldValues:
          - fieldID: 3b9b9c87
            value: '测试属性'
    FieldValues:
      required:
        - fieldID
        - type
        - value
      type: object
      properties:
        fieldID:
          description: 属性ID
          minLength: 8
          type: string
        type:
          minimum: 1
          type: integer
          description: 属性类型
        value:
          type: object
          properties: {}
          description: 属性值
    DeleteSuccessResponse:
      type: object
      properties:
        $ref: ../../../../../../../openapi-common/latest/zh/200-response-schemas.yaml
      example:
        - result: SUCCESS
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound issue'
    AddSuccessResponse:
      type: object
      properties:
        $ref: ../../../../../../../openapi-common/latest/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            id:
              type: string
              description: 工作项ID
            number:
              type: integer
              description: 工作项编号
            title:
              type: string
              description: 工作项标题
            projectID:
              type: string
              description: 工作项所属项目ID
            issueTypeID:
              type: string
              description: 工作项类型ID
            parentID:
              type: string
              description: 父工作项ID
      example:
        - result: SUCCESS
          data:
            id: 5f1f3b93
            number: 1
            title: 测试工作项
            projectID: 5f1f3b93kijun654
            issueTypeID: njkib897
            parentID: tgmlo876
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound issue'
        - result: FAIL
          errorCode: AlreadyExists
          errorMsg: 'AlreadyExists issue'
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound parentIssue'
    UpdateSuccessResponse:
      type: object
      properties:
        $ref: ../../../../../../../openapi-common/latest/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            id:
              type: string
              description: 工作项ID
            number:
              type: integer
              description: 工作项编号
            title:
              type: string
              description: 工作项标题
            projectID:
              type: string
              description: 工作项所属项目ID
            issueTypeID:
              type: string
              description: 工作项类型ID
            parentID:
              type: string
              description: 父工作项ID
      example:
        - result: SUCCESS
          data:
            id: 5f1f3b93
            number: 1
            title: 测试工作项
            projectID: 5f1f3b93kijun654
            issueTypeID: njkib897
            parentID: tgmlo876
        - result: FAIL
          errorCode: NotFound
          errorMsg: 'NotFound issue'
    ListItem:
      type: object
      properties:
        assignee:
          type: object
          properties:
            id:
              type: string
              description: 工作项负责人ID
            name:
              type: string
              description: 工作项标题
        createTime:
          type: integer
          description: 工作项创建时间
        dueDate:
          type: string
          description: 工作项截止日期
        timeEstimatedHour:
          type: integer
          description: 工作项预估工时，单位（小时）
        issueType:
          type: object
          properties:
            id:
              type: string
              description: 工作项类型ID
            name:
              type: string
              description: 工作项类型名称
        title:
          type: string
          description: 工作项标题
        number:
          type: integer
          description: 工作项编号
        creator:
          type: object
          properties:
            id:
              type: string
              description: 工作项创建者ID
            name:
              type: string
              description: 工作项创建者名称
        parent:
          type: object
          properties:
            id:
              type: string
              description: 父工作项ID
            title:
              type: string
              description: 父工作项标题
        priority:
          type: object
          properties:
            id:
              type: string
              description: 工作项优先级ID
            name:
              type: string
              description: 工作项优先级名称
        project:
          type: object
          properties:
            id:
              type: string
              description: 工作项所属项目ID
            name:
              type: string
              description: 工作项所属项目名称
        timeRemainingHour:
          type: integer
          description: 工作项剩余工时，单位（小时）
        sprint:
          type: object
          properties:
            id:
              type: string
              description: 工作项所属迭代ID
            name:
              type: string
              description: 工作项所属迭代名称
        status:
          type: object
          properties:
            id:
              type: string
              description: 工作项状态ID
            name:
              type: string
              description: 工作项状态名称
            category:
              type: string
              description: 工作项状态类型
        subIssueType:
          type: object
          properties:
            id:
              type: string
              description: 子工作项类型ID
            name:
              type: string
              description: 子工作项类型名称
        subIssueCount:
          type: integer
          description: 子工作项总数
        subIssueDoneCount:
          type: integer
          description: 子工作项状态为完成的总数
        subIssues:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: 子工作项ID
              title:
                type: string
                description: 子工作项标题
        totalTimeEstimatedHour:
          type: integer
          description: 工作项总预估工时，单位（小时）
        timeSpentHour:
          type: integer
          description: 工作项已登记工时，单位（小时）
        totalTimeRemainingHour:
          type: integer
          description: 工作项总剩余工时，单位（小时）
        id:
          type: string
          description: 工作项ID
        attachments:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: 工作项附件ID
              name:
                type: string
                description: 工作项附件名称
              createTime:
                type: integer
                description: 工作项附件创建时间
    PageInfo:
      type: object
      properties:
        count:
          type: integer
          description: 本次返回的数量
        endCursor:
          type: string
          description: 本页最后一个光标，用于翻页
        endPos:
          type: integer
          description: 本页最后一个位置
        hasNextPage:
          type: boolean
          description: 是否有下一页
        startCursor:
          type: string
          description: 本页第一个光标，用于翻页
        startPos:
          type: integer
          description: 本页第一个位置
        totalCount:
          type: integer
          description: 整个集合总数，包括本次响应中返回的
    ListSuccessResponse:
      type: object
      properties:
        $ref: ../../../../../../../openapi-common/latest/zh/200-response-schemas.yaml
        data:
          type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/ListItem'
            $ref: ../../../../../../../openapi-common/latest/zh/paging-query-response-pageInfo-schemas.yaml
    $ref: ../../../../../../../openapi-common/latest/zh/no-200-response-schemas.yaml
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://your-domain/oauth2/authorize
          tokenUrl: https://your-domain/oauth2/token
          scopes:
            write:project:issue: 新增、修改、删除工作项
            read:project:issue: 获取工作项信息
